version: '3.8'

services:
  mysql:
    container_name: database-container
    image: mysql:8.0
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      service-net-app:
  accesses:
    container_name: accesses-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://database-container:3306/accesses
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - TZ=America/Argentina/Buenos_Aires
      - USERS_API_URL=http://host.docker.internal:8283/users #usar así si se levantan dos compose por separado
    ports:
      - "8001:8001"
    networks:
      service-net-app:
    restart: on-failure

networks:
  service-net-app:

volumes:
  mysql-data: